- name: enable spi
  command: /usr/bin/raspi-config nonint do_spi 0
  become: yes

- name: install packages
  apt:
    name:
      - python3
      - python3-smbus
      - python3-spidev
      - python3-rpi.gpio
      - python3-numpy
      - python3-pyudev
      - python3-parted
      - python3-pil
      - p7zip
    state: present
  become: yes

- name: create install directory
  file:
    path: "{{ install_dir }}"
    state: directory

- name: get minecraftia font
  get_url:
    url: http://dl.dafont.com/dl/?f=minecraftia
    dest: /tmp/minecraftia.zip

- name: unarchive minecraftia font
  unarchive:
    copy: no
    src: /tmp/minecraftia.zip
    dest: "{{ install_dir }}"

- name: get 1.3inch-OLED-HAT-Code
  get_url:
    url: https://www.waveshare.com/w/upload/5/53/1.3inch-OLED-HAT-Code.7z
    dest: /tmp/1.3inch-OLED-HAT-Code.7z

# unarchive may failure with some files. ignore.
- name: unarchive 1.3inch-OLED-HAT-Code.7z
  command: /usr/bin/p7zip -f -d /tmp/1.3inch-OLED-HAT-Code.7z
  args:
    chdir: /tmp
  ignore_errors: yes

- name: copy libraries
  copy:
    src: "{{ item }}"
    dest: "{{ install_dir }}"
    remote_src: yes
  with_items:
    - /tmp/RaspberryPi/python3/config.py
    - /tmp/RaspberryPi/python3/SH1106.py

- name: copy scripts
  copy:
    src: "{{ item }}"
    dest: "{{ install_dir }}"
    mode: 0755
  with_items:
    - oledscreen.py
    - imagewriter.py

- name: copy config file
  template:
    src: config.ini
    dest: "{{ install_dir }}"

- name: copy imagewriter.service
  template:
    src: imagewriter.service
    dest: /etc/systemd/system/imagewriter.service
  become: yes

- name: enable imagewriter.service
  systemd:
    name: imagewriter.service
    enabled: yes
    state: restarted
  become: yes
